apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: maicmi/auth
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: maicmi/client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: maicmi/tickets
    context: tickets
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}